[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
optimizer = true
optimizer_runs = 200    # Low value for tests

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
